spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5435/autosalon_order
    username: autosalon
    password: autosalon
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql
  rabbitmq:
    host: localhost
    port: 5672
    username: autosalon
    password: autosalon
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/autosalon/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
